import uuid
import random
from datetime import datetime, timedelta
from faker import Faker
from .base import BaseSchema

_faker = Faker()

CATEGORIES      = ["Electronics", "Clothing", "Books", "Home & Garden",
                   "Sports", "Beauty", "Toys", "Automotive", "Food", "Music"]
PAYMENT_METHODS = ["credit_card", "debit_card", "paypal", "crypto", "bank_transfer"]
STATUSES        = ["pending", "processing", "shipped", "delivered", "returned", "cancelled"]


def _random_past_datetime(days: int = 365) -> str:
    delta = timedelta(
        days=random.randint(0, days),
        hours=random.randint(0, 23),
        minutes=random.randint(0, 59),
        seconds=random.randint(0, 59),
    )
    return (datetime.utcnow() - delta).strftime("%Y-%m-%dT%H:%M:%S")


class EcommerceSchema(BaseSchema):
    """
    13 raw ecommerce fields generated by Faker.
    Spark will add 10 derived columns in the next stage.
    """

    @property
    def name(self) -> str:
        return "ecommerce"

    def generate_record(self) -> dict:
        return {
            "order_id":         str(uuid.uuid4()),
            "customer_id":      str(uuid.uuid4()),
            "customer_name":    _faker.name(),
            "customer_email":   _faker.email(),
            "customer_country": _faker.country(),
            "product_id":       str(uuid.uuid4()),
            "product_name":     _faker.catch_phrase(),
            "category":         random.choice(CATEGORIES),
            "unit_price":       round(random.uniform(1.0, 999.99), 2),
            "quantity":         random.randint(1, 10),
            "order_timestamp":  _random_past_datetime(days=365),
            "payment_method":   random.choice(PAYMENT_METHODS),
            "status":           random.choice(STATUSES),
        }
